skills:
  basic:
    - 'Ruby': 10
    - 'Rails': 9
    - 'Javascript': 5
  js:
    - 'Coffeescript': 6
  html:
    - 'HTML5': 3
    - 'HAML': 5
    - 'Slim': 2
    - 'ERB': 1
  css:
    - 'CSS3': 3
    - 'SCSS': 5
    - 'Sass': 3
    - 'LESS': 1
  sql:
    - 'SQL': 3
  databases:
    - 'MySQL': 3
    - 'PostgreSQL': 6
    - 'Redis': 4
  js_frameworks:
    - 'jQuery': 6
    - 'Backbone.js': 6
    - 'Marionette.js': 6
    - 'RequireJS': 6
  css_frameworks:
    - 'Bootstrap': 4
    - 'Foundation': 4
  testing_frameworks:
    - 'RSpec': 6
    - 'Cucumber': 6
    - 'Capybara': 4
    - 'Mocha': 4
    - 'Konacha': 4
  ci_and_code_quality:
    - 'Jenkins': 6
    - 'Rubocop': 1
  mobile:
    - 'Cordova': 4
  deployment:
    - 'Capistrano': 3
    - 'Vagrant': 3
  tools:
    - 'Git': 6
    - 'Sublime Text': 1
    - 'OS X': 2
    - 'Homebrew': 2
  web_servers:
    - 'Nginx': 3
    - 'Apache': 3
    - 'Unicorn': 3
    - 'Passenger': 3
  services:
    - 'Heroku': 5
    - 'GitHub': 5
    - 'Amazon S3': 3
    - 'Amazon EC2': 3
  methods:
    - 'Test Driven Development': 4
    - 'Scrum': 5
